# Generated by Django 2.1.7 on 2019-04-01 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 22, 54, 53, 271257), verbose_name='date published'),
        ),
    ]
